/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.dynamics;

import org.dynamics.db.Db;
import org.dynamics.db.LevelDb;
import org.dynamics.model.Person;
import org.dynamics.reader.CsvFileReader;
import org.dynamics.reader.Reader;
import org.dynamics.ui.CommonFrame;
import org.dynamics.ui.FindFrame;
import org.dynamics.util.Utility;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.StringWriter;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class Library  extends CommonFrame {
    private Map<String, Map<String, ActionListener>> men = new LinkedHashMap<>();
    private Map<String, ActionListener> menuItems = new LinkedHashMap<>();
    private Db db = new LevelDb();
    public Library(String title) throws UnsupportedLookAndFeelException, ClassNotFoundException, InstantiationException, IllegalAccessException, IOException {
        super(title);
        menuItems.put("Find",(ActionEvent e)->{
            try {
                JComboBox<String> comboBox = new JComboBox<String>(db.keys());
                confirmation("hello",()->comboBox);
                String keySelected = comboBox.getSelectedItem().toString();
                if(keySelected!= null){
                    FindFrame findFrame = new FindFrame("Find");
                    List<Person> persons = db.find(keySelected);
                    findFrame.addDetails(Person.keys(), Utility.converter(persons));
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                alert(ex.getMessage());
            }
        });
        menuItems.put("Import",(ActionEvent e)->{
            try {
                fileChooser().ifPresent(filePath->{
                    Reader<Person> reader = null;
                    try {
                        reader = new CsvFileReader(filePath);
                        List<Person> persons =  reader.read();
                        persons.forEach(System.out::println);
                        String key = LocalDateTime.now().toString();
                        db.insert(key,persons);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                        alert(ex.getMessage());
                    }
                });

            } catch (Exception ex) {
                ex.printStackTrace();
                alert(ex.getMessage());
            }
        });
        men.put("File", menuItems);
        super.menuBar(men);
    }
    public static void main(String args[]) throws UnsupportedLookAndFeelException, ClassNotFoundException, InstantiationException, IllegalAccessException, IOException {
        Library library = new Library("Dynamcis 101 MMA");
    }
}
